version: '3.9'

services:
  dash:
    # This is for that asking the container to execute the main.py
    command: python3 app/app_flask.py
    # The image I upload to my docker hub
    image: kyithinnu/ait-ml-dash:2
    # For MAC M1 user
    platform: linux/x86_64
    # This will ask DASH to run on 0.0.0.0 and port 80
    # build:
    #   context: .
    #   dockerfile: .Dockerfile
    environment:
      - FLASK_APP=app_flask.py 
      - FLASK_ENV=production
    # This is important for asking Traefik to use your container.
    # volumes:
    #   - ./source_code:/root/sourceCode
    labels:
      # Allow Traefik to talk with your service
      - traefik.enable=true
      # Tell Traefik to use port 80
      - traefik.http.services.flask-router.loadbalancer.server.port=80
      # This config you domain name. By default, your subdomain is <service_name>-<folder_name>
      # If you which to change the subdomain name, you uncomment the below configuration
      - traefik.http.routers.flask-router.rule=Host(`st124087.ml2023.cs.ait.ac.th`)
      # Below is for enable SSL.
      - traefik.http.routers.flask-router.tls=true
      - traefik.http.routers.flask-router.tls.certresolver=production
      - traefik.http.routers.flask-router.entrypoints=websecure
    # This define network. You would need to keep it like this.
    networks:
      - default
      - traefik_default

# Keep it like this too.
networks:
  default:
  traefik_default:
    external: true